[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "/out"
  functions = "functions"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/_next/static/:splat"
  status = 200
  force = true
  conditions = {Path = "/_next/static/*"}

[[redirects]]
  from = "/*"
  to = "/api/:splat"
  status = 200
  force = true
  conditions = {Path = "/api/*"}

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  conditions = {Path = "/.netlify/functions/*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  BROWSER = "none"
  PORT = "3000"

[context.development.environment]
  BROWSER = "none"
  PORT = "3000"